### ISSUE TITLE
other face attr transfer?

### ISSUE THREAD

**Issue by cshopping** [avivga/overlord#4]
Thanks for your excellent work, have you done other attribute transfer? such as glasses without to with? thx

**Comment by avivga** [comment]
Hello,
Thanks for your interest in our work.

We haven't tried other attributes than the ones in this repository. 
You are welcome to checkout our followup work, [ZeroDIM](https://github.com/avivga/zerodim), in which we have tried a few more, including glasses (although the general setting is different).

Good luck!

**Comment by cshopping** [comment]
OK, thank you response.
Good luck
